name: CI - Run API Tests

on:
  #push:
  #  branches:
  #    - development
  workflow_dispatch:
    inputs:
      marker:
        description: 'Insert Marker or Suite'
        required: false
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Establecer variables de entorno desde secrets
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV
          echo "ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }}" >> $GITHUB_ENV
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> $GITHUB_ENV

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar tests con pytest y generar reporte Allure
        run: |
          pytest --disable-warnings -v ${{ github.event.inputs.marker }} --alluredir=reports/allure-results

      # Cargar historial de reportes anteriores (para mantener histórico en Allure)
      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # Generar reporte HTML usando la acción oficial de Allure
      - name: Build test report
        uses: allure-framework/allure2-action@v1
        if: always()
        with:
          results: reports/allure-results
          history: allure-history
          output: allure-report

      # Publicar en GitHub Pages
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
